public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        byte box = 3;
        short apple = -129;
        int car = 2;
        long bedroom = 100;
        float paper = 7.7777777f;
        double bubble = 8.888888888888888;
        System.out.println(box);
        System.out.println(apple);
        System.out.println(car);
        System.out.println(bedroom);
        System.out.println(paper);
        System.out.println(bubble);
        System.out.println("Задача 2");
        float a = 27.12f;
        System.out.println(a);
        long b = 987678965549L;
        System.out.println(b);
        float c = 2.786f;
        System.out.println(c);
        short d = 569;
        System.out.println(d);
        short e = -159;
        System.out.println(e);
        short f = 27897;
        System.out.println(f);
        byte g = 67;
        System.out.println(g);
        System.out.println("Задача 3");
        byte teacher1 = 23;
        byte teacher2 = 27;
        byte teacher3 = 30;
        short list = 480;
        short sheetsPerStudent = (short) (list / (teacher1 + teacher2 + teacher3));
        System.out.println("На каждого ученика рассчитано " + sheetsPerStudent + " листов бумаги.");
        System.out.println("Задача 4");
        byte machine1Min = 16 / 2;
        short machine20Min = (short) (machine1Min * 20);
        short machine2400Min = (short) 60 * 24;
        short machine24_1 = (short) (machine2400Min * machine1Min);
        int machine24_3 = 3 * machine24_1;
        int machine24_30 = 30 * machine24_1;
        System.out.println("За 20 минут машина произвела " +machine20Min+ " штук бутылок");
        System.out.println("За сутки машина произвела " +machine24_1+ " штук бутылок");
        System.out.println("За 3 дня машина произвела " +machine24_3+ " штук бутылок");
        System.out.println("За 1 месяц машина произвела " +machine24_30+ " штук бутылок");
        System.out.println("Задача 5");
        byte totalCans = 120;
        byte whitePaint = 2;
        byte brownPaint = 4;
        byte result1 = 4 + 2;
        byte result2 = (byte) (totalCans / result1);
        byte result3 = (byte) (result2 * whitePaint);
        byte result4 = (byte) (result2 * brownPaint);
        System.out.println("В школе, где " + result2 + " классов, нужно " + result3 + " банок белой краски и " + result4 + " банок коричневой краски.");
        System.out.println("Задача 6");
        short bananas = (short) 5 * 80;
        byte milk = 105;
        short iceCream = (short) 2*100;
        short eggs = (short) 4*70;
        short totalWeight = (short) (bananas + milk + iceCream + eggs);
        System.out.println(totalWeight);
        float fromGramsToKg = (float) totalWeight / 1000;
        System.out.println(fromGramsToKg);
        System.out.println("Задача 7");
        short purposeGram = 7000;
        short gram1 = 250;
        short gram2 = 500;
        short totalGram1 = (short) (purposeGram / gram1);
        short totalGram2 = (short) (purposeGram / gram2);
        short averageValue = (short) ((gram1 + gram2) / 2);
        System.out.println(totalGram1);
        System.out.println(totalGram2);
        System.out.println(averageValue);
        System.out.println("Задача 8");
        int Masha = 67760;
        int Denis = 83690;
        int Kristina = 76230;
        int resultMasha10Percent = (Masha / 10);
        int resultDenis10Percent = (Denis / 10);
        int resultKristina10Percent = (Kristina / 10);
        int MashaPlus10Percent = (Masha + resultMasha10Percent);
        int DenisPlus10Percent = (Denis + resultDenis10Percent);
        int KristinaPlus10Percent = (Kristina + resultKristina10Percent);
        int MashaYear1 = (Masha * 12);
        int DenisYear1 = (Denis * 12);
        int KristinaYear1 = (Kristina * 12);
        int MashaYear1Plus10Percent = (MashaPlus10Percent * 12);
        int DenisYear1Plus10Percent = (DenisPlus10Percent * 12);
        int KristinaYear1Plus10Percent = (KristinaPlus10Percent * 12);
        int DifferenceMashaYear1Plus10Percent = (MashaYear1Plus10Percent - MashaYear1);
        int DifferenceDenisYear1Plus10Percent = (DenisYear1Plus10Percent - DenisYear1);
        int DifferenceKristinaYear1Plus10Percent = (KristinaYear1Plus10Percent - KristinaYear1);
        System.out.println("Маша теперь получает " + MashaPlus10Percent + " рублей. Годовой доход вырос на " + DifferenceMashaYear1Plus10Percent + " рублей");
        System.out.println("Денис теперь получает " + DenisPlus10Percent + " рублей. Годовой доход вырос на " + DifferenceDenisYear1Plus10Percent + " рублей");
        System.out.println("Кристина теперь получает " + KristinaPlus10Percent + " рублей. Годовой доход вырос на " + DifferenceKristinaYear1Plus10Percent + " рублей");
        System.out.println("Всё.");
    }
}